// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Data struct {
	ProductSummaries []*ProductSummaries `json:"product_summaries,omitempty"`
}

type Enrichment struct {
	BuyURL *string `json:"buy_url,omitempty"`
}

type Fulfillment struct {
	ProductID                       *string            `json:"product_id,omitempty"`
	IsOutOfStockInAllStoreLocations *bool              `json:"is_out_of_stock_in_all_store_locations,omitempty"`
	ScheduledDelivery               *ScheduledDelivery `json:"scheduled_delivery,omitempty"`
	StoreOptions                    []*StoreOptions    `json:"store_options,omitempty"`
	ShippingOptions                 *ShippingOptions   `json:"shipping_options,omitempty"`
}

type GroceryObject struct {
	Data *Data `json:"data,omitempty"`
}

type InStoreOnly struct {
	AvailabilityStatus *string `json:"availability_status,omitempty"`
}

type Item struct {
	IsLimitedTimeOffer        *bool                      `json:"is_limited_time_offer,omitempty"`
	RelationshipTypeCode      *string                    `json:"relationship_type_code,omitempty"`
	ProductVendors            []*ProductVendors          `json:"product_vendors,omitempty"`
	MerchandiseClassification *MerchandiseClassification `json:"merchandise_classification,omitempty"`
	Enrichment                *Enrichment                `json:"enrichment,omitempty"`
	ProductDescription        *ProductDescription        `json:"product_description,omitempty"`
}

type MerchandiseClassification struct {
	ClassID      *int `json:"class_id,omitempty"`
	DepartmentID *int `json:"department_id,omitempty"`
}

type OrderPickup struct {
	AvailabilityStatus *string `json:"availability_status,omitempty"`
	PickupDate         *string `json:"pickup_date,omitempty"`
	GuestPickSLA       *int    `json:"guest_pick_sla,omitempty"`
	LocationLocale     *string `json:"location_locale,omitempty"`
}

type ProductDescription struct {
	Title *string `json:"title,omitempty"`
}

type ProductSummaries struct {
	Typename    *string      `json:"typename,omitempty"`
	Tcin        *string      `json:"tcin,omitempty"`
	Fulfillment *Fulfillment `json:"fulfillment,omitempty"`
	Item        *Item        `json:"item,omitempty"`
}

type ProductVendors struct {
	ID *string `json:"id,omitempty"`
}

type ScheduledDelivery struct {
	AvailabilityStatus                 *string `json:"availability_status,omitempty"`
	LocationAvailableToPromiseQuantity *int    `json:"location_available_to_promise_quantity,omitempty"`
}

type Services struct {
	ShippingMethodID     *string `json:"shipping_method_id,omitempty"`
	MinDeliveryDate      *string `json:"min_delivery_date,omitempty"`
	MaxDeliveryDate      *string `json:"max_delivery_date,omitempty"`
	IsTwoDayShipping     *bool   `json:"is_two_day_shipping,omitempty"`
	IsBaseShippingMethod *bool   `json:"is_base_shipping_method,omitempty"`
}

type ShippingOptions struct {
	AvailabilityStatus        *string     `json:"availability_status,omitempty"`
	LoyaltyAvailabilityStatus *string     `json:"loyalty_availability_status,omitempty"`
	Services                  []*Services `json:"services,omitempty"`
}

type Store struct {
	LocationName *string `json:"location_name,omitempty"`
}

type StoreOptions struct {
	SearchResponseStoreType            *string      `json:"search_response_store_type,omitempty"`
	LocationAvailableToPromiseQuantity *int         `json:"location_available_to_promise_quantity,omitempty"`
	LocationID                         *string      `json:"location_id,omitempty"`
	InStoreOnly                        *InStoreOnly `json:"in_store_only,omitempty"`
	OrderPickup                        *OrderPickup `json:"order_pickup,omitempty"`
	Store                              *Store       `json:"store,omitempty"`
}
